image: babel/android-dev

stages:
  - build
  - test
  - analysis
  - external

build:
  stage: build
  cache:
    paths:
      - app/build/
  script:
    - gradle --daemon --stacktrace --parallel clean build -x test
  environment: develop
  tags:
    - android
    - build
  only:
    - develop
    - master

test:
  stage: test
  cache:
    paths:
      - app/build/
  script:
    - gradle -a --daemon --stacktrace test
  environment: develop
  tags:
    - android
    - test
  only:
    - develop
    - master

sonar:
  stage: analysis
  script:
    -  gradle -a --no-daemon --stacktrace --parallel -q build sonarqube
  environment: develop
  tags:
    - android
    - sonar
  only:
    - develop
    - master

# Workarround sonarqube + gradle in GitLab-ci (Crea automáticamente un tarea sonarqube, con
# el estado extenal y siempre es fallida). Con esto no porovoca el fallo de la propia construcción.
sonarqube:
  stage: external
  allow_failure: true
  script: ""
  tags:
    - android
  only:
    - develop
    - master